name: Build Windows Binaries

on:
  pull_request:
  push:
    tags: ['v*']
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Install GNU Make
        run: choco install make --no-progress -y

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Install Intel compiler & libraries (primarily lapack is needed)
        run: conda install -c https://software.repos.intel.com/python/conda/ -c conda-forge mkl==2025.2 mkl-devel==2025.2 mkl-static==2025.2 ifx_win-64==2025.2 --yes

      - name: Setup env
        shell: pwsh
        run: |
          echo "MKLROOT=C:\Miniconda\envs\test\Library" >> $env:GITHUB_ENV
          echo "C:\Miniconda\envs\test\Library\bin" >> $env:GITHUB_PATH
          echo "INCLUDE=C:\Miniconda\envs\test\Library\include\intel64\ilp64;$env:INCLUDE" >> $env:GITHUB_ENV

      # Ensures MSVC link.exe is on PATH before Git's link, which ifx would otherwise pick up
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: cmd
        run: make -f Makefile.win

      - name: Get version
        id: get_version
        shell: bash
        run: |
          git fetch --all --tags
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries-${{ steps.get_version.outputs.VERSION }}
          path: |
            bldgrds.exe
            MakeGrids.exe
            build_derivs.exe
