name: Build Windows Binaries

on:
  pull_request:
  push:
    tags: ['v*']
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Install GNU Make
        run: choco install make --no-progress -y

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Install Intel compiler & libraries (primarily lapack is needed)
        run: conda install -c https://software.repos.intel.com/python/conda/ -c conda-forge mkl==2025.2 mkl-devel==2025.2 mkl-static==2025.2 ifx_win-64==2025.2 --yes

      - name: Setup env
        run: |
          echo MKLROOT=C:\Miniconda\envs\test\Library>> %GITHUB_ENV%
          echo PATH=C:\Miniconda\envs\test\Library\bin;%PATH%>> %GITHUB_ENV%
          echo INCLUDE=C:\Miniconda\envs\test\Library\include\intel64\ilp64;%INCLUDE%>> %GITHUB_ENV%

      - name: Build
        shell: cmd
        run: make -f Makefile.win

      - name: Get version
        id: get_version
        shell: bash
        run: |
          git fetch --all --tags
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries-${{ steps.get_version.outputs.VERSION }}
          path: |
            bldgrds.exe
            MakeGrids.exe
            build_derivs.exe
