name: Build Windows Binaries

on:
  pull_request:
  push:
    tags: ['v*']
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Install GNU Make
        run: choco install make --no-progress -y

      - name: Setup Intel Fortran (ifx)
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: intel
          version: '2025.2'

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"

      - name: Install Intel MKL
        run: conda install -c https://software.repos.intel.com/python/conda/ -c conda-forge mkl-devel==2025.2 --yes

      - name: get conda info
        run: conda info

      - name: Set MKLROOT
        shell: bash
        run: |
          echo "MKLROOT=C:\Miniconda\Library" >> $GITHUB_ENV

      - name: Build
        shell: cmd
        run: make -f Makefile.win

      - name: Get version
        id: get_version
        shell: bash
        run: |
          git fetch --all --tags
          echo "VERSION=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries-${{ steps.get_version.outputs.VERSION }}
          path: |
            bldgrds.exe
            MakeGrids.exe
            build_derivs.exe
